create table if not exists char_map (
    src_char character varying unique ,
    dest_char character varying unique
);

insert into
    char_map (src_char, dest_char)
values ('m', 'r'),
       ('B', 'F'),
       ('5', '3'),
       ('3', 'n'),
       ('E', '2'),
       ('O', 'o'),
       ('R', 'V'),
       ('V', 'P'),
       ('U', 's'),
       ('s', '+'),
       ('t', 'C'),
       ('L', 'X'),
       ('M', 'T'),
       ('Y', '0'),
       ('6', 'Z'),
       ('g', 'O'),
       ('i', '7'),
       ('l', 'Y'),
       ('o', 'K'),
       ('F', 'p'),
       ('P', 'k'),
       ('T', 'N'),
       ('9', 'Q'),
       ('j', 'U'),
       ('q', 'a'),
       ('z', '4'),
       ('Q', 'W'),
       ('f', 'z'),
       ('r', 'v'),
       ('D', 'B'),
       ('K', 'c'),
       ('p', 'm'),
       ('C', 't'),
       (' ', 'd'),
       ('d', 'I'),
       ('v', '6'),
       ('N', 'u'),
       ('8', '@'),
       ('x', '-'),
       ('.', 'E'),
       ('-', '5'),
       ('J', 'g'),
       ('0', 'L'),
       ('4', 'j'),
       ('2', 'q'),
       ('b', 'G'),
       ('k', 'M'),
       ('w', 'J'),
       ('G', '8'),
       ('h', 'e'),
       ('1', 'f'),
       ('S', 'w'),
       ('W', 'D'),
       ('X', 'b'),
       ('/', '!'),
       ('n', 'l'),
       ('A', '1'),
       ('H', 'h'),
       ('I', 'A'),
       (':', 'R'),
       ('y', 'i'),
       ('Z', 'x'),
       ('7', '9'),
       ('a', 'H'),
       ('c', '$'),
       ('e', 'S'),
       ('u', 'y')
    on conflict do nothing ;